apiVersion: v1
kind: Service
metadata:
  name: {{.Pipeline.SvcPrefix}}-{{.Service.Name}}-{{.Pipeline.ID}}
  namespace: {{.Pipeline.Namespace}}
spec:
  ports:
{{- range .Ports}}
    - name: {{.Name}}
      port: {{.Port}}
      protocol: TCP
      targetPort: {{.Port}}
{{- end }}
  selector:
    pipeline: {{.Pipeline.Name}}
    id: "{{.Pipeline.ID}}"
    task: {{.Service.Task}}
